### PR TITLE
Create COMMITTERS.csv

### PR DESCRIPTION
**Pull request by jmertic**
Signed-off-by: John Mertic <jmertic@linuxfoundation.org>

### CODE REVIEW

**Comment by jmertic** [comment]
@shreeji818 can you review?

**Review by shreeji818 — APPROVED** [review]

**Review by shreeji818 — APPROVED** [review]

**Review by shreeji818 — APPROVED** [review]
Reviewed.. Looks like I lost write access.

**Review by shreeji818 — APPROVED** [review]
We also need to add couple additional persons from my team
Conner Ferrguson, conner.ferguson@ibm.com, Conner-IBM
Maria Sueli Almeida, sueli@us.ibm.com, suelialmeida

**Comment by jmertic** [comment]
Added now.

@shreeji818 @ehrocha @itsBryantP Can each of you submit a review so this can be merged?

**Review by shreeji818 — APPROVED** [review]

**Review by shreeji818 — APPROVED** [review]

**Pull request merged**
